config/routes.rb
Facebook::Application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  resources :messages
  resources :users do
    member do
      post :add_friend      
    end
  end
  root to: 'users#show' 

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post 
  validates :body, presence: true
end

app/models/friends_list.rb
class FriendsList < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/message.rb
class Message < ActiveRecord::Base
	validates :body, presence: true
	belongs_to :user
end

app/models/messages.rb
class Messages < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates :body, presence: true
	has_many :comments, dependent: :destroy, order: 'created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friends_lists
	has_many :friends, through:  :friends_lists
	has_many :posts
	has_many :comments
	has_many :messages 
	has_many :received_messages, foreign_key: 'receiver', class_name: 'Message'	
  has_many :sent_messages, foreign_key: 'user_id', class_name: 'Message'	
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery 
  before_filter :authenticate_user!
  
  def after_sign_in_path_for(user)
    user_path(user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# POST /posts/1/comments
  def create
    @post = Post.find_by_id params[:post_id] 
    @comment = @post.comments.create comment_params 
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js
      else
        format.js { render :js => "alert('comment cannot be empty');" }
      end
    end    
  end
  
  #DELETE /posts/1/comments/1
  def destroy
    post = Post.find_by_id params[:post_id]
    @comment = post.comments.find_by_id params[:id] 
    respond_to do |format|
      if @comment.destroy
        format.js
      else
        format.js { render :js => "alert('error deleting comment');" }
      end
    end
  end

  private
  def comment_params
      params.require(:comment).permit(:body)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # GET /messages
  def index
    @user_received_messages = current_user.received_messages
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages
  def create
    @message = current_user.messages.create message_params 
    user = User.where(email: message_params[:receiver]).first 
    respond_to do |format|	
      if !user.nil? && message_params[:body].present?
        @message.receiver = user.id
        @message.save 
        format.html { redirect_to messages_path(@user), notice: t(:message_send) }
      else
        format.html { redirect_to new_message_path, notice: t(:message_error) }
      end
    end 
  end

  private
  def message_params
      params.require(:message).permit(:body, :receiver)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]
  
  # GET /posts
  def index
    @my_posts = Post.where user_id: current_user 
    @friends_posts = Post.where user_id: current_user.friends
    @post = Post.new
  end

  # GET /posts/1
  def show
    @comments = @post.comments
  end

  # POST /posts
  def create
    @post = current_user.posts.create post_params 
    respond_to do |format|
      if @post.save
        format.js
      else
        format.js { render js: "alert('Post could not be created');" }
      end
    end
  end

  #DELETE /posts/1
  def destroy
    @post.destroy
    respond_to do |format|
      format.js
    end
  end
  
  private
  def set_post
    @post = Post.find_by_id params[:id]
  end

  def post_params
    params.require(:post).permit(:body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	# GET /users/1
	def show
		@user = (User.find_by_id params[:id]) || current_user 
	end
	
	# GET /users/1
	def index
		@users = User.all
	end

	# POST /users/1
	def add_friend 
		friend = current_user.friends_lists.where friend_id: params[:id] 
		if !friend
			current_user.friends_lists.create params[:id]
			flag = true
    end
    respond_to do |format|
			if flag
				format.html { redirect_to current_user, notice: t(:friend_added) }
			else
				flash[:error] = ["Friend already exists"] 
				format.html { redirect_to current_user }	
			end
		end
	end
end

app/views/comments/_comment.html.erb
<div class="comment" id="<%= comment.id %>">
  <%= comment.user.email %>
  <%= comment.body %>
  <% if comment.user == current_user %>
	 <%= link_to 'Destroy', post_comment_path(@post, comment, format: :js),
              remote: true,
              data: { confirm: 'Are you sure?' },
              :method => :delete %>  
   <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build], :html => { class: 'form-horizontal'}, remote: true) do |f| %>
  <fieldset>
    <div class = "control-group">
      <%= f.label :comment , class: "control-label"%><br />
      <div class = "controls">
        <%= f.text_area :body, class: "text-field comment-field" %>
      </div>
    </div>
    <div class="form-actions">
      <%= f.submit nil, class: "btn btn-primary comment-botton"%>
    </div>
  </fieldset>
<% end %>

app/views/comments/create.js.erb
$('#com').append("<%= j render @comment %>");

app/views/comments/destroy.js.erb
$('.comment#<%= @comment.id %>').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="navbar-header">
      <%= link_to "facebook", '#', id: "logo", class: 'navbar-brand' %>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% if current_user.present? %>
        <%= link_to "My Profile", user_path(current_user), class: 'navbar-brand' %>
      <%end%>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>
  </nav>
  <%= image_tag "facebook.jpeg", alt: "Facebook", class: "image" %>
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>
  <% if flash[:error] %>
    <div id = "errorExplanation">
      <p><%= pluralize(flash[:error].count, "error") %></p>
        <ul>
          <% flash[:error].each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class="span"><%= yield %></div>
      <div class="span center">
        <h2>About Us</h2>
        <p>Facebook is a social website to connect people.</p>        
      </div>
    </div>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message,html: { class: 'form-horizontal'}) do |f| %>
  <div class="controll-group">
    <%= f.label :send_to, class: "conroll-label" %><br />
    <div class="controlls">
      <%= f.text_area :receiver, class: "text-area" %>
    </div>
  </div>
  <div class="controll-group">
    <%= f.label :body, class: "conroll-label" %><br />
    <div class="controlls">
    <%= f.text_area :body, class: "text-area" %>
  </div>
  <div class="form-actions">
    <%= f.submit :Send, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/messages/index.html.erb
<% content_for :title do %>
	Messages
<% end %>
</br>
<table class="table table-striped">
  <h2>Your Messages</h2>
  <ul>
    <% @user_received_messages.each do |message| %>
  	 	<li><% sender = message.user_id %>
  	 		<h4><%= User.find(sender).email %></h4>
		  	<%=  message.body %>
  		</li>
    <% end %>
    </br> 
  </ul>
</table>
<%= link_to 'send message', new_message_path, class: "btn btn-mini" %>

app/views/messages/new.html.erb
<h3>Send Message</h3>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/posts/_form.html.erb
<%= form_for @post, html: { class: 'form-horizontal'}, remote: true do |post_form| %>
  <fieldset>
    <% if @post.errors.any? %>
      <div id = "errorExplanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class = "control-group" >
      <%= post_form.label :body, class: "control-label" %><br />
      <div class = "contols">
        <%= post_form.text_field :body, class: "text-field post-field" %>
      </div>
    </div>
    <br />
    <div class = "form-actions">
      <%= post_form.submit nil, class: "btn btn-primary post-button" %>
    </div>
  </fieldset>
<% end %>

app/views/posts/_friends_posts.html.erb
<table class = 'table table-striped'>
  <thead>
    <tr>
      <th>Friend's posts</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friends_posts.each do |post| %>
      <tr>
        <td><%= post.user.email %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'show post', post_path(post), class: 'btn btn-mini' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_my_posts.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th>Your posts</th>
    </tr>
  </thead>

  <tbody>
    <% @my_posts.find_each do |post| %>
      <%= render partial: 'post', locals: {post: post} %>
    <% end %>
  </tbody>
</table>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.body %></td>
  <td><%= link_to 'Destroy', post, method: :delete, remote: true, data: { confirm: 'Are you sure?', class: 'btn btn-mini' } %></td>
  <td><%= link_to 'show post', post_path(post), class: 'btn btn-mini' %></td>
</tr>

app/views/posts/create.js.erb
$('.my_posts').append("<%= j render @post %>");

app/views/posts/destroy.js.erb
$('.my_posts#<%= @post.id %>').remove();

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<%= render partial: 'friends_posts' %>
<div class = "my_posts" id = "@post.id">
  <%= render partial: 'my_posts' %> 
</div>
<br>
<h1>New Post</h1>
<div>
  <%= render partial: 'form' %>
</div>

app/views/posts/show.html.erb
<h2>Post</h2>
<%= @post.body %>
<h2>Comments</h2>
<div id='com'>
  <%= render @post.comments %>
</div>
<h2>Add a comment:</h2>
<%= render partial: 'comments/form' %>

app/views/users/index.html.erb
<h2>Other Users</h2>
<% @users.each do |user| %>
  <table class = "table table-striped">
    <div class = "user">
      <p>
        <strong><%= h user.email if user != current_user %></strong>
            <%= link_to "Add Friend", add_friend_user_path(user), method: :post, :class => "btn btn-primary" %>
     	  <% end %>
      </p>
    </div>
  </table>
<% end %>

app/views/users/show.html.erb
<% content_for :title do %>
	My Profile
<% end %>
<p><h3><%= link_to "Find Friends", users_path %></h3></p>
<table class ="table table-striped"> 
  <h2>Your Friends</h2>
  <ul>
    <% @user.friends.each do |user| %>
      <li><%=  user.email %></li>
    <% end %>  
  </ul>
</table>
</br>
<p><%= link_to "Posts",  posts_path, :class => "btn btn-primary" %></p>
</br>
<p><%= link_to "Messages",  messages_path, :class => "btn btn-primary" %></p>
</br>
<p><%= link_to "Add Friends",  users_path, :class => "btn btn-primary" %></p>